package cz.muni.fi.pv168.gui;

import cz.muni.fi.pv168.receptar.Ingredience;
import cz.muni.fi.pv168.receptar.IngredienceException;
import cz.muni.fi.pv168.receptar.IngredienceManagerImpl;
import cz.muni.fi.pv168.receptar.Recipe;
import cz.muni.fi.pv168.receptar.RecipeCategory;
import cz.muni.fi.pv168.receptar.RecipeCategoryException;
import cz.muni.fi.pv168.receptar.RecipeCategoryManager;
import cz.muni.fi.pv168.receptar.RecipeCategoryManagerImpl;
import cz.muni.fi.pv168.receptar.RecipeException;
import cz.muni.fi.pv168.receptar.RecipeManagerImpl;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sql.DataSource;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ivana
 */
public class Receptar extends javax.swing.JPanel {
    private final RecipeCategoryManagerImpl recipeCategoryManager;
    private final RecipeManagerImpl recipeManager;
    private final IngredienceManagerImpl ingredienceManager;
    private Recipe recipe;
   
    /**
     * Creates new form Receptar
     * @param ds
     */
    public Receptar(DataSource ds) {
        initComponents();
        recipeCategoryManager = new RecipeCategoryManagerImpl(ds);
        recipeManager = new RecipeManagerImpl(ds);
        ingredienceManager = new IngredienceManagerImpl(ds);
        this.setCategories();
        this.setRecipeNameList();
    }
    
    /**
     * Sets categories into table, list and combo box
     */
    public void setCategories() {
        List<RecipeCategory> categories;
        try {
            categories = recipeCategoryManager.findAllRecipeCategories();
        } catch (RecipeCategoryException ex) {
            Logger.getLogger(Receptar.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
        int listLength = categories.size();
        
        Object[] columnNames = {"Category Name"};
        DefaultTableModel listTableModel;
        listTableModel = new DefaultTableModel(columnNames, 0);
        
        DefaultListModel listModel;
        listModel = new DefaultListModel();
        
        DefaultComboBoxModel comboBoxModel;
        comboBoxModel = new DefaultComboBoxModel();
        
        for (int i = 0; i < listLength; i++){
            listTableModel.addRow(new Object[]{categories.get(i).getTitle()});
            listModel.addElement(categories.get(i).getTitle());
            comboBoxModel.addElement(categories.get(i).getTitle());
        }
         
        jCategoryNameTable.setModel(listTableModel);
        jCategoriesList.setModel(listModel);
        jSelectCategory.setModel(comboBoxModel);
        jEditCategory.setModel(comboBoxModel);
    }
    
    /**
     * Sets ingrediences into list
     * @param recipe 
     */
    public void setIngrediences(Recipe recipe){       
        this.recipe = recipe;
        List<Ingredience> ingrediences = recipe.getIngrediences();
        
        Object[] columnNames = {"Title", "Amount", "Unit"};
        DefaultTableModel listTableModel;
        listTableModel = new DefaultTableModel(columnNames, 0);
        
        for (int i = 0; i < ingrediences.size(); i++){
            String title = ingrediences.get(i).getTitle();
            double amount = ingrediences.get(i).getAmount();
            String unit = ingrediences.get(i).getUnit();
            listTableModel.addRow(new Object[]{title, amount, unit});
        }
        jRecipeIngrediencesTable.setModel(listTableModel);
    }
    
    /**
     * Sets recipe names into list
     */
    public void setRecipeNameList(){
        List<Recipe> recipes;
        try {
            recipes = recipeManager.findAllRecipes();
        } catch (RecipeException ex) {
            Logger.getLogger(Receptar.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
        int listLength = recipes.size();
        DefaultListModel listModel = new DefaultListModel();
        for (int i = 0; i < listLength; i++){
            
            listModel.addElement(recipes.get(i).getTitle());
        }
        jRecipesList.setModel(listModel);
    }
    
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeleteCategoryjDialog = new javax.swing.JDialog();
        AddRecipejFrame = new javax.swing.JFrame();
        jRecipeTitleLabel = new javax.swing.JLabel();
        jNewRecipeTitle = new javax.swing.JTextField();
        jTimeLabel = new javax.swing.JLabel();
        jInstrLabel = new javax.swing.JLabel();
        jTimeUnitLabel = new javax.swing.JLabel();
        jNoteLabel = new javax.swing.JLabel();
        jNewNote = new javax.swing.JTextField();
        jInstructions = new javax.swing.JScrollPane();
        jNewInstructions = new javax.swing.JTextArea();
        jOkButton = new javax.swing.JButton();
        jCancelButton = new javax.swing.JButton();
        jSelectCategory = new javax.swing.JComboBox();
        jCategoryLabel = new javax.swing.JLabel();
        jTimeSpinner = new javax.swing.JSpinner();
        EditRecipejFrame = new javax.swing.JFrame();
        jLabel16 = new javax.swing.JLabel();
        jEditTitle = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jEditNote = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        jEditInstructions = new javax.swing.JTextArea();
        jOkEditButton = new javax.swing.JButton();
        jCancelEditButton = new javax.swing.JButton();
        jEditCategory = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jEditTime = new javax.swing.JSpinner();
        DeleteRecipejDialog = new javax.swing.JDialog();
        jButton14 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        DeleteRecipejDialog1 = new javax.swing.JDialog();
        jButton24 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jButton25 = new javax.swing.JButton();
        receptarPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("receptarPU").createEntityManager();
        recipecategoriesQuery = java.beans.Beans.isDesignTime() ? null : receptarPUEntityManager.createQuery("SELECT r FROM Recipecategories r");
        recipecategoriesList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : recipecategoriesQuery.getResultList();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jRecipesPanel = new javax.swing.JPanel();
        jRecipeViewScrollPane = new javax.swing.JScrollPane();
        jRecipeViewPanel = new javax.swing.JPanel();
        jInstructionsLabel = new javax.swing.JLabel();
        jRecipeInstructionsScrollPane = new javax.swing.JScrollPane();
        jRecipeInstructions = new javax.swing.JTextArea();
        jIngrediencesLabel = new javax.swing.JLabel();
        jRecipeIngrediencesScrollPane = new javax.swing.JScrollPane();
        jRecipeIngrediencesTable = new javax.swing.JTable();
        jRecipeName = new javax.swing.JLabel();
        jRecipeTime = new javax.swing.JLabel();
        jRecipeNote = new javax.swing.JLabel();
        jIngredienceUpdateButton = new javax.swing.JButton();
        jIngredienceDeleteButton = new javax.swing.JButton();
        jIngredienceAddButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jIngredienceTitle = new javax.swing.JTextField();
        jIngredienceAmount = new javax.swing.JTextField();
        jIngredienceUnit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCategoriesLabel = new javax.swing.JLabel();
        jCategoriesListScrollPain = new javax.swing.JScrollPane();
        jCategoriesList = new javax.swing.JList();
        jRecipesLabel = new javax.swing.JLabel();
        jRecipesListScrollPane = new javax.swing.JScrollPane();
        jRecipesList = new javax.swing.JList();
        jRecipesAddButton = new javax.swing.JButton();
        jRecipesDeleteButton = new javax.swing.JButton();
        jRecipesEditButton = new javax.swing.JButton();
        jCategoriesPanel = new javax.swing.JPanel();
        jCategories = new javax.swing.JScrollPane();
        jCategoryNameScrollPane = new javax.swing.JScrollPane();
        jCategoryNameTable = new javax.swing.JTable();
        jCategoriesAddButton = new javax.swing.JButton();
        jCategoriesUpdateButton = new javax.swing.JButton();
        jCategoriesDeleteButton = new javax.swing.JButton();
        categoryNameInput = new javax.swing.JTextField();

        DeleteCategoryjDialog.setTitle("Delete category");

        javax.swing.GroupLayout DeleteCategoryjDialogLayout = new javax.swing.GroupLayout(DeleteCategoryjDialog.getContentPane());
        DeleteCategoryjDialog.getContentPane().setLayout(DeleteCategoryjDialogLayout);
        DeleteCategoryjDialogLayout.setHorizontalGroup(
            DeleteCategoryjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );
        DeleteCategoryjDialogLayout.setVerticalGroup(
            DeleteCategoryjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
        );

        AddRecipejFrame.setTitle("Add a recipe");

        jRecipeTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jRecipeTitleLabel.setText("Recipe title:");

        jNewRecipeTitle.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTimeLabel.setText("Time:");

        jInstrLabel.setText("Instructions:");

        jTimeUnitLabel.setText("min");

        jNoteLabel.setText("Note:");

        jNewNote.setMinimumSize(new java.awt.Dimension(25, 22));
        jNewNote.setPreferredSize(new java.awt.Dimension(102, 22));

        jInstructions.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jNewInstructions.setColumns(20);
        jNewInstructions.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jNewInstructions.setLineWrap(true);
        jNewInstructions.setRows(5);
        jInstructions.setViewportView(jNewInstructions);

        jOkButton.setText("OK");
        jOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOkButtonActionPerformed(evt);
            }
        });

        jCancelButton.setText("Cancel");
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });

        jSelectCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSelectCategoryActionPerformed(evt);
            }
        });

        jCategoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jCategoryLabel.setText("Category:");

        javax.swing.GroupLayout AddRecipejFrameLayout = new javax.swing.GroupLayout(AddRecipejFrame.getContentPane());
        AddRecipejFrame.getContentPane().setLayout(AddRecipejFrameLayout);
        AddRecipejFrameLayout.setHorizontalGroup(
            AddRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddRecipejFrameLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(AddRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddRecipejFrameLayout.createSequentialGroup()
                        .addGroup(AddRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRecipeTitleLabel)
                            .addComponent(jNoteLabel)
                            .addComponent(jCategoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jNewNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jNewRecipeTitle)
                            .addComponent(jSelectCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(AddRecipejFrameLayout.createSequentialGroup()
                        .addGroup(AddRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jInstrLabel)
                            .addComponent(jTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jInstructions, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                            .addGroup(AddRecipejFrameLayout.createSequentialGroup()
                                .addComponent(jTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jTimeUnitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 437, Short.MAX_VALUE))
                            .addGroup(AddRecipejFrameLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(346, 346, 346))
        );
        AddRecipejFrameLayout.setVerticalGroup(
            AddRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddRecipejFrameLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(AddRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSelectCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCategoryLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRecipeTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNewRecipeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(AddRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNewNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNoteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(AddRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInstrLabel)
                    .addComponent(jInstructions, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(AddRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTimeUnitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108)
                .addGroup(AddRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOkButton)
                    .addComponent(jCancelButton))
                .addGap(45, 45, 45))
        );

        EditRecipejFrame.setTitle("Edit a recipe");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Recipe title:");

        jEditTitle.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jEditTitle.setText("Torta");

        jLabel17.setText("Time:");

        jLabel18.setText("Instructions:");

        jLabel19.setText("min");

        jLabel20.setText("Note:");

        jEditNote.setText("Cook fast!");
        jEditNote.setMinimumSize(new java.awt.Dimension(25, 22));
        jEditNote.setPreferredSize(new java.awt.Dimension(102, 22));

        jScrollPane10.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jEditInstructions.setColumns(20);
        jEditInstructions.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jEditInstructions.setLineWrap(true);
        jEditInstructions.setRows(5);
        jEditInstructions.setText("Povarime, upecieme...");
        jScrollPane10.setViewportView(jEditInstructions);

        jOkEditButton.setText("OK");
        jOkEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOkEditButtonActionPerformed(evt);
            }
        });

        jCancelEditButton.setText("Cancel");
        jCancelEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelEditButtonActionPerformed(evt);
            }
        });

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("Category:");

        javax.swing.GroupLayout EditRecipejFrameLayout = new javax.swing.GroupLayout(EditRecipejFrame.getContentPane());
        EditRecipejFrame.getContentPane().setLayout(EditRecipejFrameLayout);
        EditRecipejFrameLayout.setHorizontalGroup(
            EditRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditRecipejFrameLayout.createSequentialGroup()
                .addGroup(EditRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(EditRecipejFrameLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jOkEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jCancelEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EditRecipejFrameLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(EditRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EditRecipejFrameLayout.createSequentialGroup()
                                .addGroup(EditRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(EditRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jEditNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jEditTitle)
                                    .addComponent(jEditCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(EditRecipejFrameLayout.createSequentialGroup()
                                .addGroup(EditRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(EditRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                                    .addGroup(EditRecipejFrameLayout.createSequentialGroup()
                                        .addComponent(jEditTime, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(177, 177, 177)))))))
                .addGap(346, 346, 346))
        );
        EditRecipejFrameLayout.setVerticalGroup(
            EditRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditRecipejFrameLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(EditRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jEditTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(EditRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(EditRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(EditRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jEditTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(EditRecipejFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCancelEditButton)
                    .addComponent(jOkEditButton))
                .addGap(102, 102, 102))
        );

        jButton14.setText("No");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Do you really want to delete this recipe?");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButton15.setText("Yes");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DeleteRecipejDialogLayout = new javax.swing.GroupLayout(DeleteRecipejDialog.getContentPane());
        DeleteRecipejDialog.getContentPane().setLayout(DeleteRecipejDialogLayout);
        DeleteRecipejDialogLayout.setHorizontalGroup(
            DeleteRecipejDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteRecipejDialogLayout.createSequentialGroup()
                .addGroup(DeleteRecipejDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeleteRecipejDialogLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DeleteRecipejDialogLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel10)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        DeleteRecipejDialogLayout.setVerticalGroup(
            DeleteRecipejDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteRecipejDialogLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(DeleteRecipejDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton15)
                    .addComponent(jButton14))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jButton24.setText("No");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Do you really want to delete this ingredience?");
        jLabel27.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButton25.setText("Yes");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DeleteRecipejDialog1Layout = new javax.swing.GroupLayout(DeleteRecipejDialog1.getContentPane());
        DeleteRecipejDialog1.getContentPane().setLayout(DeleteRecipejDialog1Layout);
        DeleteRecipejDialog1Layout.setHorizontalGroup(
            DeleteRecipejDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteRecipejDialog1Layout.createSequentialGroup()
                .addGroup(DeleteRecipejDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeleteRecipejDialog1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DeleteRecipejDialog1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel27)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        DeleteRecipejDialog1Layout.setVerticalGroup(
            DeleteRecipejDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteRecipejDialog1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(DeleteRecipejDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton25)
                    .addComponent(jButton24))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jRecipeViewScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jInstructionsLabel.setText("Instructions");

        jRecipeInstructions.setEditable(false);
        jRecipeInstructions.setColumns(20);
        jRecipeInstructions.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jRecipeInstructions.setRows(5);
        jRecipeInstructionsScrollPane.setViewportView(jRecipeInstructions);

        jIngrediencesLabel.setText("Ingrediences");

        jRecipeIngrediencesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Amount", "Unit"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jRecipeIngrediencesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jRecipeIngrediencesTableMouseReleased(evt);
            }
        });
        jRecipeIngrediencesScrollPane.setViewportView(jRecipeIngrediencesTable);
        if (jRecipeIngrediencesTable.getColumnModel().getColumnCount() > 0) {
            jRecipeIngrediencesTable.getColumnModel().getColumn(0).setResizable(false);
            jRecipeIngrediencesTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jRecipeName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRecipeName.setText("Torta od mamy");

        jRecipeTime.setText("Time: 120 min");

        jRecipeNote.setText("Note: ");

        jIngredienceUpdateButton.setText("Update");
        jIngredienceUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIngredienceUpdateButtonActionPerformed(evt);
            }
        });

        jIngredienceDeleteButton.setText("Delete");
        jIngredienceDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIngredienceDeleteButtonActionPerformed(evt);
            }
        });

        jIngredienceAddButton.setText("Add");
        jIngredienceAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIngredienceAddButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Title");

        jLabel3.setText("Amount");

        jLabel4.setText("Unit");

        javax.swing.GroupLayout jRecipeViewPanelLayout = new javax.swing.GroupLayout(jRecipeViewPanel);
        jRecipeViewPanel.setLayout(jRecipeViewPanelLayout);
        jRecipeViewPanelLayout.setHorizontalGroup(
            jRecipeViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRecipeViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jRecipeViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jInstructionsLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jIngrediencesLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRecipeNote, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jRecipeViewPanelLayout.createSequentialGroup()
                        .addGroup(jRecipeViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jIngredienceDeleteButton)
                            .addGroup(jRecipeViewPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jIngredienceTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jIngredienceAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jIngredienceUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jIngredienceAddButton)
                        .addGap(18, 18, 18)
                        .addComponent(jIngredienceUpdateButton))
                    .addComponent(jRecipeIngrediencesScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                    .addComponent(jRecipeInstructionsScrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jRecipeViewPanelLayout.createSequentialGroup()
                        .addComponent(jRecipeName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRecipeTime)))
                .addGap(0, 269, Short.MAX_VALUE))
        );
        jRecipeViewPanelLayout.setVerticalGroup(
            jRecipeViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jRecipeViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jRecipeViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRecipeName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRecipeTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRecipeNote)
                .addGap(64, 64, 64)
                .addComponent(jIngrediencesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRecipeIngrediencesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jIngredienceDeleteButton)
                .addGap(7, 7, 7)
                .addGroup(jRecipeViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jIngredienceTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jIngredienceAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jIngredienceUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jIngredienceAddButton)
                    .addComponent(jIngredienceUpdateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jInstructionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRecipeInstructionsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jRecipeViewScrollPane.setViewportView(jRecipeViewPanel);

        jCategoriesLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCategoriesLabel.setText("Categories");

        jCategoriesListScrollPain.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jCategoriesListScrollPain.setViewportView(jCategoriesList);

        jRecipesLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRecipesLabel.setText("Recipes");

        jRecipesListScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jRecipesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jRecipesListMouseReleased(evt);
            }
        });
        jRecipesListScrollPane.setViewportView(jRecipesList);

        jRecipesAddButton.setText("Add");
        jRecipesAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRecipesAddButtonActionPerformed(evt);
            }
        });

        jRecipesDeleteButton.setText("Delete");
        jRecipesDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRecipesDeleteButtonActionPerformed(evt);
            }
        });

        jRecipesEditButton.setText("Edit");
        jRecipesEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRecipesEditButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jRecipesPanelLayout = new javax.swing.GroupLayout(jRecipesPanel);
        jRecipesPanel.setLayout(jRecipesPanelLayout);
        jRecipesPanelLayout.setHorizontalGroup(
            jRecipesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRecipesPanelLayout.createSequentialGroup()
                .addGroup(jRecipesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jRecipesPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jRecipesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCategoriesLabel)
                            .addComponent(jRecipesLabel)
                            .addGroup(jRecipesPanelLayout.createSequentialGroup()
                                .addComponent(jRecipesAddButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRecipesEditButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRecipesDeleteButton))))
                    .addComponent(jRecipesListScrollPane)
                    .addComponent(jCategoriesListScrollPain))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRecipeViewScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jRecipesPanelLayout.setVerticalGroup(
            jRecipesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRecipesPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jCategoriesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCategoriesListScrollPain, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRecipesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRecipesListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jRecipesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRecipesAddButton)
                    .addComponent(jRecipesDeleteButton)
                    .addComponent(jRecipesEditButton)))
            .addComponent(jRecipeViewScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Recipes", jRecipesPanel);

        jCategoryNameTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jCategoryNameTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jCategoryNameTable.getTableHeader().setReorderingAllowed(false);
        jCategoryNameTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCategoryNameTableMouseReleased(evt);
            }
        });
        jCategoryNameScrollPane.setViewportView(jCategoryNameTable);

        jCategories.setViewportView(jCategoryNameScrollPane);

        jCategoriesAddButton.setText("Add new");
        jCategoriesAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCategoriesAddButtonActionPerformed(evt);
            }
        });

        jCategoriesUpdateButton.setText("Update");
        jCategoriesUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCategoriesUpdateButtonActionPerformed(evt);
            }
        });

        jCategoriesDeleteButton.setText("Delete");
        jCategoriesDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCategoriesDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jCategoriesPanelLayout = new javax.swing.GroupLayout(jCategoriesPanel);
        jCategoriesPanel.setLayout(jCategoriesPanelLayout);
        jCategoriesPanelLayout.setHorizontalGroup(
            jCategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCategoriesPanelLayout.createSequentialGroup()
                .addComponent(jCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jCategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCategoriesAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(categoryNameInput)
                    .addComponent(jCategoriesUpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCategoriesDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 386, Short.MAX_VALUE))
        );
        jCategoriesPanelLayout.setVerticalGroup(
            jCategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCategoriesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jCategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jCategoriesPanelLayout.createSequentialGroup()
                        .addComponent(jCategoriesDeleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(categoryNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCategoriesUpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCategoriesAddButton)))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Categories", jCategoriesPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Deletes category on delete button click
     * @param evt 
     */
    private void jCategoriesDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCategoriesDeleteButtonActionPerformed
        String title = this.categoryNameInput.getText();
        RecipeCategory category;
        try {
            category = recipeCategoryManager.findRecipeCategoryByTitle(title);
            recipeCategoryManager.deleteRecipeCategory(category);
        } catch (RecipeCategoryException ex) {
            Logger.getLogger(Receptar.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setCategories();
    }//GEN-LAST:event_jCategoriesDeleteButtonActionPerformed

    /**
     * Adds new recipe on OK button click (add jform)
     * @param evt 
     */
    private void jOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOkButtonActionPerformed
        Recipe recipe = new Recipe();
        RecipeCategory cat = new RecipeCategory();
        
        try {
            cat = recipeCategoryManager.findRecipeCategoryByTitle(jSelectCategory.getSelectedItem().toString());
        } catch (RecipeCategoryException ex) {
            Logger.getLogger(Receptar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        recipe.setCategory(cat);
        recipe.setTitle(jNewRecipeTitle.getText());
        recipe.setInstructions(jNewInstructions.getText());
        recipe.setNote(jNewNote.getText());
        recipe.setTime(Integer.valueOf(jTimeSpinner.getValue().toString()));
        
        try {
            recipeManager.createRecipe(recipe);
        } catch (RecipeException ex) {
            Logger.getLogger(Receptar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        setRecipeNameList();
        AddRecipejFrame.dispose();
    }//GEN-LAST:event_jOkButtonActionPerformed

    /**
     * Updates recipe on OK button click (edit jForm)
     * TODO
     * @param evt 
     */
    private void jOkEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOkEditButtonActionPerformed
        Recipe recipe = new Recipe();
        String title = jRecipesList.getSelectedValue().toString();
        try {
            recipe = recipeManager.findRecipeByTitle(title);
            recipeManager.updateRecipe(recipe);
        } catch (RecipeException ex) {
            Logger.getLogger(Receptar.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setRecipeNameList();
        EditRecipejFrame.dispose();
    }//GEN-LAST:event_jOkEditButtonActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    /**
     * Updates category on update button click
     * TODO
     * @param evt 
     */
    private void jCategoriesUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCategoriesUpdateButtonActionPerformed
       /** String title = this.categoryNameInput.getText();
        try {
            RecipeCategory category = recipeCategoryManager.findRecipeCategoryByTitle(title);
            this.recipeCategoryManager.updateRecipeCategory(category);
        } catch (RecipeCategoryException ex) {
            Logger.getLogger(Receptar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.setCategories();*/
    }//GEN-LAST:event_jCategoriesUpdateButtonActionPerformed

    /**
     * Adds new category on add button click
     * @param evt 
     */
    private void jCategoriesAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCategoriesAddButtonActionPerformed
        String title = this.categoryNameInput.getText();
        
        RecipeCategory recipeCategory = new RecipeCategory();
        recipeCategory.setTitle(title);
        
        try {
            this.recipeCategoryManager.createRecipeCategory(recipeCategory);
        } catch (RecipeCategoryException ex) {
            Logger.getLogger(Receptar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.setCategories();
    }//GEN-LAST:event_jCategoriesAddButtonActionPerformed

    /**
     * Delets ingredience on button click
     * @param evt 
     */
    private void jIngredienceDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIngredienceDeleteButtonActionPerformed
        String title = this.jIngredienceTitle.getText();
        double amount = Double.parseDouble(jIngredienceAmount.getText());
        String unit = jIngredienceUnit.getText();
            
        List <Ingredience> ingrediences;
           
        try {
            ingrediences = ingredienceManager.findIngrediencesByTitle(title);
                for (int i = 0; i < ingrediences.size(); i++){
                    if ((ingrediences.get(i).getAmount() == amount) && (ingrediences.get(i).getUnit().equals(unit))){
                        ingredienceManager.deleteIngredience(ingrediences.get(i));
                    }
                }
        } catch (IngredienceException ex) {
            Logger.getLogger(Receptar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       // Object recipeTitle = jRecipesList.getSelectedValue();
       // try {
       //     recipe = recipeManager.findRecipeByTitle(recipeTitle.toString());
       // } catch (RecipeException ex) {
       //     Logger.getLogger(Receptar.class.getName()).log(Level.SEVERE, null, ex);
       // }
        this.setIngrediences(recipe);

    }//GEN-LAST:event_jIngredienceDeleteButtonActionPerformed

    /**
     * Updates ingredience on button click
     * TODO
     * @param evt 
     */
    private void jIngredienceUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIngredienceUpdateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIngredienceUpdateButtonActionPerformed

    /**
     * Sets selected category into categoryNameInput text field
     * @param evt 
     */
    private void jCategoryNameTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCategoryNameTableMouseReleased
        int row = this.jCategoryNameTable.getSelectedRow();
        int column = this.jCategoryNameTable.getSelectedColumn();
        Object value = jCategoryNameTable.getValueAt(row, column);
        categoryNameInput.setText(value.toString());
    }//GEN-LAST:event_jCategoryNameTableMouseReleased

    /**
     * Sets selected recipe into view scroll pane
     * @param evt 
     */
    private void jRecipesListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRecipesListMouseReleased
        Object title = jRecipesList.getSelectedValue();
        try {
            recipe = recipeManager.findRecipeByTitle(title.toString());
        } catch (RecipeException ex) {
            Logger.getLogger(Receptar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jRecipeName.setText(recipe.getTitle());
        jRecipeNote.setText(recipe.getNote());
        jRecipeTime.setText(recipe.getTime() + " min");
        setIngrediences(recipe);
        jRecipeInstructions.setText(recipe.getInstructions());
    }//GEN-LAST:event_jRecipesListMouseReleased

    /**
     * Adds ingredience on button click
     * TODO
     * @param evt 
     */
    private void jIngredienceAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIngredienceAddButtonActionPerformed
        String title = this.jIngredienceTitle.getText();
        double amount = Double.parseDouble(jIngredienceAmount.getText());
        String unit = jIngredienceUnit.getText();
        
        Ingredience ingredience = new Ingredience();
        ingredience.setTitle(title);
        ingredience.setAmount(amount);
        ingredience.setUnit(unit);
        
        
        try {
            recipeManager.addIngredienceToRecipe(ingredience, recipe);
        } catch (RecipeException ex) {
            Logger.getLogger(Receptar.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.setIngrediences(recipe);
    }//GEN-LAST:event_jIngredienceAddButtonActionPerformed

    /**
     * Selects ingredience into text fields
     * @param evt 
     */
    private void jRecipeIngrediencesTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRecipeIngrediencesTableMouseReleased
        int row = this.jRecipeIngrediencesTable.getSelectedRow();
        //Object value = jRecipeIngrediencesTable.get
        jIngredienceTitle.setText(jRecipeIngrediencesTable.getValueAt(row, 0).toString());
        jIngredienceAmount.setText(jRecipeIngrediencesTable.getValueAt(row, 1).toString());
        jIngredienceUnit.setText(jRecipeIngrediencesTable.getValueAt(row, 2).toString());
    }//GEN-LAST:event_jRecipeIngrediencesTableMouseReleased

    /**
     * Pop up new jform for adding recipe
     * @param evt 
     */
    private void jRecipesAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRecipesAddButtonActionPerformed
        AddRecipejFrame.setSize(800, 600);
        AddRecipejFrame.setVisible(true);
    }//GEN-LAST:event_jRecipesAddButtonActionPerformed

    /**
     * Cancels adding new recipe
     * @param evt 
     */
    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
        AddRecipejFrame.dispose();
    }//GEN-LAST:event_jCancelButtonActionPerformed

    /**
     * Delets selected recipe
     * @param evt 
     */
    private void jRecipesDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRecipesDeleteButtonActionPerformed
        Recipe recipe = new Recipe();
        try {
            recipe = recipeManager.findRecipeByTitle(jRecipesList.getSelectedValue().toString());
            recipeManager.deleteRecipe(recipe);
        } catch (RecipeException ex) {
            Logger.getLogger(Receptar.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setRecipeNameList();
    }//GEN-LAST:event_jRecipesDeleteButtonActionPerformed

    /**
     * Pops up new jform for editing recipe
     * TODO
     * @param evt 
     */
    private void jRecipesEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRecipesEditButtonActionPerformed
        EditRecipejFrame.setVisible(true);
        EditRecipejFrame.setSize(800, 600);
        
        Recipe recipe = new Recipe();
        try {
            recipe = recipeManager.findRecipeByTitle(jRecipesList.getSelectedValue().toString());
        } catch (RecipeException ex) {
            Logger.getLogger(Receptar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jEditCategory.setSelectedItem(recipe.getCategory().getTitle());
        jEditTitle.setText(recipe.getTitle());
        jEditNote.setText(recipe.getNote());
        jEditInstructions.setText(recipe.getInstructions());
        jEditTime.setValue(recipe.getTime());
        
    }//GEN-LAST:event_jRecipesEditButtonActionPerformed

    private void jSelectCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSelectCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSelectCategoryActionPerformed

    /**
     * Cencels editing recipe
     * @param evt 
     */
    private void jCancelEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelEditButtonActionPerformed
        EditRecipejFrame.dispose();
    }//GEN-LAST:event_jCancelEditButtonActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame AddRecipejFrame;
    private javax.swing.JDialog DeleteCategoryjDialog;
    private javax.swing.JDialog DeleteRecipejDialog;
    private javax.swing.JDialog DeleteRecipejDialog1;
    private javax.swing.JFrame EditRecipejFrame;
    private javax.swing.JTextField categoryNameInput;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jCancelButton;
    private javax.swing.JButton jCancelEditButton;
    private javax.swing.JScrollPane jCategories;
    private javax.swing.JButton jCategoriesAddButton;
    private javax.swing.JButton jCategoriesDeleteButton;
    private javax.swing.JLabel jCategoriesLabel;
    private javax.swing.JList jCategoriesList;
    private javax.swing.JScrollPane jCategoriesListScrollPain;
    private javax.swing.JPanel jCategoriesPanel;
    private javax.swing.JButton jCategoriesUpdateButton;
    private javax.swing.JLabel jCategoryLabel;
    private javax.swing.JScrollPane jCategoryNameScrollPane;
    private javax.swing.JTable jCategoryNameTable;
    private javax.swing.JComboBox jEditCategory;
    private javax.swing.JTextArea jEditInstructions;
    private javax.swing.JTextField jEditNote;
    private javax.swing.JSpinner jEditTime;
    private javax.swing.JTextField jEditTitle;
    private javax.swing.JButton jIngredienceAddButton;
    private javax.swing.JTextField jIngredienceAmount;
    private javax.swing.JButton jIngredienceDeleteButton;
    private javax.swing.JTextField jIngredienceTitle;
    private javax.swing.JTextField jIngredienceUnit;
    private javax.swing.JButton jIngredienceUpdateButton;
    private javax.swing.JLabel jIngrediencesLabel;
    private javax.swing.JLabel jInstrLabel;
    private javax.swing.JScrollPane jInstructions;
    private javax.swing.JLabel jInstructionsLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextArea jNewInstructions;
    private javax.swing.JTextField jNewNote;
    private javax.swing.JTextField jNewRecipeTitle;
    private javax.swing.JLabel jNoteLabel;
    private javax.swing.JButton jOkButton;
    private javax.swing.JButton jOkEditButton;
    private javax.swing.JScrollPane jRecipeIngrediencesScrollPane;
    private javax.swing.JTable jRecipeIngrediencesTable;
    private javax.swing.JTextArea jRecipeInstructions;
    private javax.swing.JScrollPane jRecipeInstructionsScrollPane;
    private javax.swing.JLabel jRecipeName;
    private javax.swing.JLabel jRecipeNote;
    private javax.swing.JLabel jRecipeTime;
    private javax.swing.JLabel jRecipeTitleLabel;
    private javax.swing.JPanel jRecipeViewPanel;
    private javax.swing.JScrollPane jRecipeViewScrollPane;
    private javax.swing.JButton jRecipesAddButton;
    private javax.swing.JButton jRecipesDeleteButton;
    private javax.swing.JButton jRecipesEditButton;
    private javax.swing.JLabel jRecipesLabel;
    private javax.swing.JList jRecipesList;
    private javax.swing.JScrollPane jRecipesListScrollPane;
    private javax.swing.JPanel jRecipesPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JComboBox jSelectCategory;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jTimeLabel;
    private javax.swing.JSpinner jTimeSpinner;
    private javax.swing.JLabel jTimeUnitLabel;
    private javax.persistence.EntityManager receptarPUEntityManager;
    private java.util.List<cz.muni.fi.pv168.gui.Recipecategories> recipecategoriesList;
    private javax.persistence.Query recipecategoriesQuery;
    // End of variables declaration//GEN-END:variables
}
